# Generated by Django 2.2 on 2019-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20190515_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
